version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 229803190678.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the SpringBoot app...
      - mvn clean install
      - echo Building the Docker image...          
      - docker build -t tutget/main:latest .
      - docker tag tutget/main:latest 229803190678.dkr.ecr.us-east-1.amazonaws.com/tutget/main:latest     
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 229803190678.dkr.ecr.us-east-1.amazonaws.com/tutget/main:latest
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' tutget-main 229803190678.dkr.ecr.us-east-1.amazonaws.com/tutget/main:latest > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
